name: CI/CD Pipeline

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build-and-push:
    runs-on: self-hosted
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.CR_PAT }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Build and push Docker image
        uses: docker/build-push-action@v4
        with:
          context: .
          push: true
          tags: |
            ghcr.io/${{ github.repository }}:latest
            ghcr.io/${{ github.repository }}:${{ github.sha }}

      - name: Update GitOps repository
        shell: powershell  # Use "powershell" instead of "pwsh"
        env:
         GIT_TOKEN: ${{ secrets.GITOPS_PAT }}
        run: |
          # Configure git credentials
          git config --global credential.helper store
          "https://$env:GIT_TOKEN:x-oauth-basic@github.com" | Out-File -FilePath "$env:USERPROFILE\.git-credentials" -Encoding ASCII

          # Clean up and clone repo
          Remove-Item -Recurse -Force gitops -ErrorAction SilentlyContinue
          git clone https://github.com/maaz2020/grade-api-gitops.git gitops
          cd gitops

          # Update image tag
          (Get-Content deployment.yaml) -replace "image: ghcr.io/maaz2020/kubernetes-cicd-tutorial:.*", "image: ghcr.io/maaz2020/kubernetes-cicd-tutorial:${{ github.sha }}" | Set-Content deployment.yaml

          # Commit and push changes
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          git add deployment.yaml
          git commit -m "Update image to ${{ github.sha }}"
    git push -f "https://$env:GIT_TOKEN@github.com/maaz2020/grade-api-gitops.git" main
